# DB_URL debe tener el formato:
# postgresql://127.0.0.1:5433/data_base_name
# Spring agrega automáticamente el prefijo jdbc:
spring.application.name=motor-scoring-crediticio
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
