CREATE TABLE solicitante (
    id_solicitante BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    numero_documento VARCHAR(15) NOT NULL,
    ingresos_mensuales NUMERIC(15,2) NOT NULL,
    deudas_mensuales NUMERIC(15,2) NOT NULL,
    numero_moras INTEGER NOT NULL,
    historial_crediticio VARCHAR(10) NOT NULL,
    antiguedad_laboral NUMERIC(5,2) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_solicitante_numero_documento UNIQUE (numero_documento),
    CONSTRAINT ck_solicitante_ingresos_mensuales CHECK (ingresos_mensuales >= 0),
    CONSTRAINT ck_solicitante_deudas_mensuales CHECK (deudas_mensuales >= 0),
    CONSTRAINT ck_solicitante_numero_moras CHECK (numero_moras >= 0),
    CONSTRAINT ck_solicitante_antiguedad_laboral CHECK (antiguedad_laboral >= 0),
    CONSTRAINT ck_solicitante_historial_crediticio CHECK (historial_crediticio IN ('BUENO', 'REGULAR', 'MALO'))
);
