CREATE TABLE regla_scoring (
    id_regla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_riesgo BIGINT NOT NULL,
    operador VARCHAR(2) NOT NULL,
    valor_condicion VARCHAR(255) NOT NULL,
    puntaje INTEGER NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'ACTIVA',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_regla_scoring_riesgo FOREIGN KEY (id_riesgo) REFERENCES riesgo (id_riesgo),
    CONSTRAINT uq_regla_scoring_condicion UNIQUE (id_riesgo, operador, valor_condicion),
    CONSTRAINT ck_regla_scoring_operador CHECK (operador IN ('=', '>', '>=', '<', '<=')),
    CONSTRAINT ck_regla_scoring_puntaje CHECK (puntaje BETWEEN -100 AND 100),
    CONSTRAINT ck_regla_scoring_estado CHECK (estado = 'ACTIVA')
);
