CREATE TABLE evaluacion (
    id_evaluacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitante BIGINT NOT NULL,
    fecha_evaluacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evaluacion_solicitante FOREIGN KEY (id_solicitante) REFERENCES solicitante (id_solicitante)
);

CREATE TABLE detalle_evaluacion (
    id_detalle_evaluacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evaluacion BIGINT NOT NULL,
    id_regla BIGINT NOT NULL,
    operador_aplicado VARCHAR(2) NOT NULL,
    valor_condicion_aplicado VARCHAR(255) NOT NULL,
    puntaje_regla_aplicado INTEGER NOT NULL,
    condicion_cumplida BOOLEAN NOT NULL,
    puntaje_obtenido INTEGER NOT NULL,
    CONSTRAINT fk_detalle_evaluacion_evaluacion FOREIGN KEY (id_evaluacion) REFERENCES evaluacion (id_evaluacion),
    CONSTRAINT fk_detalle_evaluacion_regla FOREIGN KEY (id_regla) REFERENCES regla_scoring (id_regla),
    CONSTRAINT ck_detalle_evaluacion_operador CHECK (operador_aplicado IN ('=', '>', '>=', '<', '<='))
);
